apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: es-cluster-state
spec:
  schedule: "*/15 * * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: analytics-svc-container
            image: ivukotic/ml_platform_auto:latest
            command: ["/es-cluster-state.sh"]
            # args: ["/DDM/run.sh", "ddm_accounting"]
          restartPolicy: Never
