apiVersion: v1
kind: Pod
metadata:
  name: base
  namespace: aaas
spec:
  containers:
  - name: aaas-container
    image: atlasanalyticsservice/alarmandalertservice:latest
    args: ["sleep", "36500000"]
  restartPolicy: Always
