apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: es-cluster-state
  namespace: aaas
spec:
  schedule: "5 0 * * 0"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aaas-container
            image: atlasanalyticsservice/alarmandalertservice:latest
            command: ["/es-make-backup.sh"]
            volumeMounts:
            - name: config-volume
              mountPath: "/config"
              readOnly: true
          volumes:       
          - name: config-volume
            secret:
              secretName: config
          restartPolicy: Never
