apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fts-aggregator
  namespace: aaas
spec:
  schedule: "18 12 * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: aaas-container
              image: atlasanalyticsservice/alarmandalertservice:latest
              command: ["/fts-aggregator.sh"]
              volumeMounts:
                - name: config-volume
                  mountPath: "/config"
                  readOnly: true
          volumes:
            - name: config-volume
              secret:
                secretName: config
          restartPolicy: Never
