apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job-task-indexing
  namespace: aaas
spec:
  schedule: "25 4,10,16,22 * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aaas-container
            image: atlasanalyticsservice/alarmandalertservice:latest
            command: ["/job-task-indexing.sh"]
            volumeMounts:
            - name: google-secret-vol
              mountPath: "/secrets"
              readOnly: true
          volumes:
          - name: google-secret-vol
            secret:
              secretName: google-secret
          restartPolicy: Never
