apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job-task-indexing
  namespace: aaas
spec:
  schedule: "25 4,10,16,22 * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: aaas-container
              image: atlasanalyticsservice/alarmandalertservice:latest
              command: ["/job-task-indexing.sh"]
              env:
                - name: MAILGUN_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: mailgun-secret
                      key: api-key
              volumeMounts:
                - name: config-volume
                  mountPath: "/config"
                  readOnly: true
          volumes:
            - name: config-volume
              secret:
                secretName: config
          restartPolicy: Never
