apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: sending-mails
  namespace: aaas
spec:
  schedule: "3 0,3,6,9,12,15,18,21  * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aaas-container
            image: atlasanalyticsservice/alarmandalertservice:latest
            command: ["/sending-mails.sh"]
            volumeMounts:
            - name: google-secret-vol
              mountPath: "/secrets"
              readOnly: true
          volumes:
          - name: google-secret-vol
            secret:
              secretName: google-secret
          restartPolicy: Never
