apiVersion: v1
kind: Pod
metadata:
  name: test-mail
  namespace: aaas
spec:
  containers:
  - name: aaas-container
    image: atlasanalyticsservice/alarmandalertservice:latest
    args: ["test-mail.sh"]
    env:
    - name: MAILGUN_API_KEY
      valueFrom:
        secretKeyRef:
          name: mailgun-secret
          key: api-key
    volumeMounts:
    - name: google-secret-vol
      mountPath: "/secrets"
      readOnly: true
  volumes:
  - name: google-secret-vol
    secret:
      secretName: google-secret
  restartPolicy: Always
