apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: es-cluster-state
  namespace: aaas
spec:
  schedule: "*/15 * * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aaas-container
            image: atlasanalyticsservice/alarmandalertservice:latest
            command: ["/es-cluster-state.sh"]
          restartPolicy: Never
