apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: top-users
  namespace: aaas
spec:
  schedule: "*/15 * * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aaas-container
            image: atlasanalyticsservice/alarmandalertservice:latest
            command: ["/top-users.sh"]
            volumeMounts:
            - name: google-secret-vol
              mountPath: "/tmp"
              readOnly: true
          volumes:
          - name: google-secret-vol
            secret:
              secretName: google-secret
          restartPolicy: Never
