apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: user-reports
  namespace: aaas
spec:
  schedule: "12 2 * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: aaas-container
            image: atlasanalyticsservice/alarmandalertservice:latest
            command: ["/user-reports.sh"]
            env:
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mailgun-secret
                  key: api-key
            volumeMounts:
            - name: google-secret-vol
              mountPath: "/secrets"
              readOnly: true
          volumes:
          - name: google-secret-vol
            secret:
              secretName: google-secret
          restartPolicy: Never
