apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: packet-loss
  namespace: aaas
spec:
  schedule: "1 */3 * * *"
  suspend: false
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: aaas-container
              image: atlasanalyticsservice/alarmandalertservice:latest
              command: ["/packet-loss.sh"]
              volumeMounts:
                - name: google-secret-vol
                  mountPath: "/secrets"
                  readOnly: true
                - name: config-volume
                  mountPath: "/config"
                  readOnly: true
          volumes:
            - name: google-secret-vol
              secret:
                secretName: google-secret
            - name: config-volume
              secret:
                secretName: config
          restartPolicy: Never
